language: shell
sudo: required

os:
  - linux
  - osx

env:
  global:
    - SHFMT_URL=https://github.com/mvdan/sh/releases/download/v0.4.0/shfmt_v0.4.0_linux_amd64

addons:
  apt:
    sources:
    - debian-sid    # Grab shellcheck from the Debian repo (o_O)
    packages:
    - shellcheck

install:
  - if [ "$TRAVIS_OS_NAME" = 'osx' ]; then
      brew update && brew install openssl;
      brew info openssl;
    fi
  
script:
  - echo "TEST_LOCAL=$TEST_LOCAL"
  - nc -h 2>&1



matrix:
  fast_finish: true
  
  
